server:
  port: 8010
  servlet:
    context-path: /paiya-eventmanager/api

# Database
spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: paiya_eventmanager
      username: paiya
      password: paiya
